spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.DriverSpy
    username: root
    password: 123456
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/imooc-springcloud?characoerEncoding=utf-8&useSSl=false
  jpa:
    show-sql: true
logging:
  level:
    com.imooc: debug
